# -------------------------------------------------------------
# Required GitHub Token Permissions for this workflow:
#
# For the secret used as GH_TOKEN, ensure the following scopes:
#
# 1. Administration (Read and write)
# 2. Metadata (Read-only)
# 3. Custom properties (Read and write)
#
# If using an organization-level token, ensure the token has:
# - Custom properties permission for the organization
#
# These permissions are required to allow the workflow to create forks
# in the organization and manage repository properties.
# -------------------------------------------------------------
name: Fork Repo

on:
  workflow_dispatch:
    inputs:
      num_forks:
        description: 'Number of forks to create'
        required: true
        default: '1'
      name_prefix:
        description: 'Prefix for fork names'
        required: false
        default: 'WG'
      org:
        description: 'Target organization for forks'
        required: true
        default: 'Forrester-Wave-Demo-Q3-2025'
      nwo:
        description: 'Repository org/repo to fork'
        required: false
        default: 'Forrester-Wave-Demo-Q3-2025/WebGoat'

jobs:
  fork-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Run PowerShell to clone and push to multiple repos
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.FORK_TOKEN }}
        run: |
          $numForks = [int]('${{ github.event.inputs.num_forks }}')
          $prefix = '${{ github.event.inputs.name_prefix }}'
          $org = '${{ github.event.inputs.org }}'
          $nwo = '${{ github.event.inputs.nwo }}'
          
          # Extract just the repository name from the full repo path (org/repo)
          $repoName = $nwo.Split('/')[-1]
          
          git clone --bare "https://github.com/$nwo.git"
          cd "${repoName}.git"
          
          # Loop through and create each repository
          for ($i = 1; $i -le $numForks; $i++) {
            $suffix = $i.ToString('000')
            $forkName = "$prefix-$suffix"

            # Create a new empty repository
            echo "Creating new repo: $org/$forkName"
            gh repo create "$org/$forkName" --internal

            # Push to the repository
            echo "Pushing to $org/$forkName"
            git push --mirror "https://$env:GH_TOKEN@github.com/$org/$forkName.git"

            # Set default branch to main
            echo "Setting default branch to main for $org/$forkName"
            gh repo edit $org/$forkName --default-branch main

            # Set custom property 'repo-type' to 'synthetic' - will fail if not available
            echo "Setting custom property 'repo-type' to 'synthetic' for $org/$forkName"
            gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$org/$forkName/properties/values" -f "properties[][property_name]=repo-type" -f "properties[][value][]=synthetic"            
          }
