# -------------------------------------------------------------
# Required GitHub Token Permissions for this workflow:
#
# For the secret used as GH_TOKEN, ensure the following scopes:
#
# 1. Administration (Read and write)
# 2. Metadata (Read-only)
# 3. Custom properties (Read and write)
#
# If using an organization-level token, ensure the token has:
# - Custom properties permission for the organization
#
# These permissions are required to allow the workflow to create forks
# in the organization and manage repository properties.
# -------------------------------------------------------------
name: Fork Repo

on:
  workflow_dispatch:
    inputs:
      num_forks:
        description: 'Number of forks to create'
        required: true
        default: '3'
      name_prefix:
        description: 'Prefix for fork names'
        required: false
        default: 'WG'
      org:
        description: 'Target organization for forks'
        required: true
        default: 'Forrester-Wave-Demo-Q3-2025'
      repo:
        description: 'Repository org/repo to fork'
        required: false
        default: 'Forrester-Wave-Demo-Q3-2025/WebGoat'

jobs:
  fork-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Run PowerShell to clone and fork
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.FORK_TOKEN }}
        run: |
          $numForks = [int]('${{ github.event.inputs.num_forks }}')
          $prefix = '${{ github.event.inputs.name_prefix }}'
          $org = '${{ github.event.inputs.org }}'
          $repo = '${{ github.event.inputs.repo }}'

          for ($i = 1; $i -le $numForks; $i++) {
            $suffix = $i.ToString('000')
            $forkName = "$prefix-$suffix"
            echo "Creating fork: $forkName"
            gh repo fork $repo --org $org --fork-name $forkName --clone=false --remote=false

            # Wait for a moment to ensure the fork is fully created
            echo "Waiting for fork to be fully ready..."
            Start-Sleep -Seconds 3
            
            # Set custom property 'repo-type' to 'synthetic' - will fail if not available
            echo "Setting custom property 'repo-type' to 'synthetic' for $org/$forkName"
            gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$org/$forkName/properties/values" -f "properties[][property_name]=repo-type" -f "properties[][value]=[\"synthetic\"]"
          }
